//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.TenonAccessibilityChecker {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class contents {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal contents() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.TenonAccessibilityChecker.contents", typeof(contents).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors and Warnings.
        /// </summary>
        internal static string DefaultCertainity {
            get {
                return ResourceManager.GetString("DefaultCertainity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAA.
        /// </summary>
        internal static string DefaultLevel {
            get {
                return ResourceManager.GetString("DefaultLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title: \n{0}\n  \nStandards:{1}  \nDescription:\n{2}\n  \nCode Snippet:\n{3}.
        /// </summary>
        internal static string ErrorFormat {
            get {
                return ResourceManager.GetString("ErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TenonIo.
        /// </summary>
        internal static string Linklabeltext1 {
            get {
                return ResourceManager.GetString("Linklabeltext1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confidence.
        /// </summary>
        internal static string Linklabeltext2 {
            get {
                return ResourceManager.GetString("Linklabeltext2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}  ({1})&quot;.
        /// </summary>
        internal static string messsageformat {
            get {
                return ResourceManager.GetString("messsageformat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OKMessage {
            get {
                return ResourceManager.GetString("OKMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn about the Tenon service and how features like Confidence scores can be used.
        /// </summary>
        internal static string TenonAccessibilityLabelContent {
            get {
                return ResourceManager.GetString("TenonAccessibilityLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Occurred..
        /// </summary>
        internal static string TenonAPIError {
            get {
                return ResourceManager.GetString("TenonAPIError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200.
        /// </summary>
        internal static string TenonApiResponseSuccess {
            get {
                return ResourceManager.GetString("TenonApiResponseSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success. Tenon found {0} errors and {1} warnings. Results are displayed in the Error List..
        /// </summary>
        internal static string TenonAPISuccess {
            get {
                return ResourceManager.GetString("TenonAPISuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f06c7b9200dbf58e7bf7f0889b5abb97.
        /// </summary>
        internal static string TenonAppId {
            get {
                return ResourceManager.GetString("TenonAppId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://tenon.io/documentation/understanding-request-parameters.php.
        /// </summary>
        internal static string TenonDocumentation {
            get {
                return ResourceManager.GetString("TenonDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://tenon.io/.
        /// </summary>
        internal static string TenonIo {
            get {
                return ResourceManager.GetString("TenonIo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenon Key is Mandatory..
        /// </summary>
        internal static string TenonKeyValidatioMessage {
            get {
                return ResourceManager.GetString("TenonKeyValidatioMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://tenon.io/register.php.
        /// </summary>
        internal static string TenonRegistrationLink {
            get {
                return ResourceManager.GetString("TenonRegistrationLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://tenon.io/api/.
        /// </summary>
        internal static string TenonService {
            get {
                return ResourceManager.GetString("TenonService", resourceCulture);
            }
        }
    }
}
